#!/usr/bin/env sh

set -e

sed -i '/supervisord --nodaemon/d' /docker-entrypoint

/docker-entrypoint

php -i
php -i | grep 'expose_php => Off'
php -i | grep 'max_file_uploads => 120'
php -i | grep 'max_input_vars => 10'
php -i | grep 'log_errors => Off'
php -i | grep 'memory_limit => 1G'
php -i | grep 'post_max_size => 1G'
php -i | grep 'upload_max_filesize => 1G'
php -i | grep 'apc.enable_cli => Off'
php -i | grep 'apc.shm_segments => 1'
php -i | grep 'apc.shm_size => 64M'
php -i | grep 'opcache.enable => On'
php -i | grep 'opcache.huge_code_pages => On'
php -i | grep 'opcache.max_accelerated_files => 16229'
php -i | grep 'opcache.validate_timestamps => On'
php -i | grep 'opcache.revalidate_freq => 60'
php -i | grep 'date.timezone => Europe/Bucharest'
php -i | grep 'imagick module => enabled'
if ! grep -q CRON_COMMAND_1 /etc/crontabs/root; then echo "ERROR: CRON_COMMAND_1 not found"; exit 1; else echo "CRON_COMMAND_1 found"; fi
if ! grep -q CRON_COMMAND_2 /etc/crontabs/root; then echo "ERROR: CRON_COMMAND_2 not found"; exit 1; else echo "CRON_COMMAND_2 found"; fi
if ! grep -q CRON_COMMAND_3 /etc/crontabs/root; then echo "ERROR: CRON_COMMAND_3 not found"; exit 1; else echo "CRON_COMMAND_3 found"; fi
