version: "3.5"

services:
  sut:
    # image: cristiroma/nginx-php-fpm:php56
    # container_name: php56
    build:
      context: .
    environment:
      - PHP_INI_OVERRIDES=expose_php=Off;max_execution_time=120;max_file_uploads=120;max_input_vars=10;log_errors=Off;memory_limit=1G;post_max_size=1G;upload_max_filesize=1G;date.timezone=Europe/Bucharest
      - CRON_SCHEDULE_COMMAND="* * * * * sudo -u www-data /bin/echo CRON_COMMAND_1"
      - CRON_SCHEDULE_COMMAND1="* * * * * sudo -u www-data /bin/echo CRON_COMMAND_2"
      - CRON_SCHEDULE_COMMAND2="* * * * * sudo -u www-data /bin/echo CRON_COMMAND_3"
    volumes:
      - ./docker-entrypoint-test:/docker-entrypoint-test
    entrypoint: "/docker-entrypoint-test"