#!/usr/bin/env sh

set -e

sed -i '/supervisord --nodaemon/d' /docker-entrypoint

/docker-entrypoint

php -i | grep 'expose_php => Off'
php -i | grep 'max_file_uploads => 120'
php -i | grep 'max_input_vars => 10'
php -i | grep 'log_errors => Off'
php -i | grep 'memory_limit => 1G'
php -i | grep 'post_max_size => 1G'
php -i | grep 'upload_max_filesize => 1G'
# No APC support yet enabled
# php -i | grep 'apc.enable_cli => Off'
# php -i | grep 'apc.shm_segments => 1'
# php -i | grep 'apc.shm_size => 64M'
php -i | grep 'opcache.enable => On'
php -i | grep 'opcache.max_accelerated_files => 16229'
php -i | grep 'opcache.validate_timestamps => On'
php -i | grep 'opcache.revalidate_freq => 60'
php -i | grep 'date.timezone => Europe/Bucharest'
