version: "3.5"

services:
  sut:
    # image: cristiroma/nginx-php-fpm:php74
    # container_name: php74
    build:
      context: .
    environment:
      - php_expose_php="Off"
      - php_max_file_uploads="120"
      - php_max_input_vars="10"
      - php_log_errors="On"
      - php_memory_limit="1G"
      - php_post_max_size="1G"
      - php_upload_max_filesize="1G"
      - CRON_SCHEDULE_COMMAND="* * * * * sudo -u www-data /bin/echo CRON_COMMAND_1"
      - CRON_SCHEDULE_COMMAND1="* * * * * sudo -u www-data /bin/echo CRON_COMMAND_2"
      - CRON_SCHEDULE_COMMAND2="* * * * * sudo -u www-data /bin/echo CRON_COMMAND_3"
    volumes:
      - ./docker-entrypoint-test:/docker-entrypoint-test
    entrypoint: "/docker-entrypoint-test"