#!/usr/bin/env sh

set -e

for var in $(env | grep 'php_'); do
  var1=$(echo "$var" | sed 's/php_//g')
  echo "$var1" >> /usr/local/etc/php/conf.d/php-ini-overrides.ini
done

supervisord --nodaemon --configuration /etc/supervisord.conf